### ISSUE TITLE
simple-example.js and npm test is throwing the below errors

### ISSUE THREAD

**Issue by Santhoshas** [SistemaStrategy/HiveThrift#2]
C:\Users\santhosh\Downloads\HiveThrift-master\node_modules\thrift\lib\nodejs\lib\thrift\connection.js:171
        throw e;
        ^

TypeError: Cannot read property 'sessionHandle' of undefined
    at C:\Users\santhosh.sakthivel\Downloads\HiveThrift-master\src\HiveThriftClient.js:243:28
    at C:\Users\santhosh.sakthivel\Downloads\HiveThrift-master\src\HiveThriftClient.js:68:4
    at client._reqs.(anonymous function) (C:\Users\santhosh.sakthivel\Downloads\HiveThrift-master\node_modules\thrift\lib\nodejs\lib\thrift\connection.js:151:13)
    at exports.Client.TCLIServiceClient.recv_OpenSession (C:\Users\santhosh.sakthivel\Downloads\HiveThrift-master\lib\gen-nodejs\TCLIService.js:2111:12)
    at C:\Users\santhosh.sakthivel\Downloads\HiveThrift-master\node_modules\thrift\lib\nodejs\lib\thrift\connection.js:157:41
    at Socket.<anonymous> (C:\Users\santhosh.sakthivel\Downloads\HiveThrift-master\node_modules\thrift\lib\nodejs\lib\thrift\buffered_transport.js:48:5)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)

**Comment by Santhoshas** [comment]
Unable to get response from the server code. Program is getting exit without printing the error.
